/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/landing/About.vue')['default']
    Achiements: typeof import('./src/components/landing/Achiements.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    Blog: typeof import('./src/components/landing/Blog.vue')['default']
    CareerObjective: typeof import('./src/components/landing/CareerObjective.vue')['default']
    ColorModeButton: typeof import('./src/components/ColorModeButton.vue')['default']
    Education: typeof import('./src/components/landing/Education.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Hero: typeof import('./src/components/landing/Hero.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    PalaroidItem: typeof import('./src/components/PalaroidItem.vue')['default']
    Projects: typeof import('./src/components/landing/Projects.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skills: typeof import('./src/components/landing/Skills.vue')['default']
    Skils: typeof import('./src/components/landing/Skils.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UMain: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Main.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
    WorkExperience: typeof import('./src/components/landing/WorkExperience.vue')['default']
  }
}
